<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true" CodeFile="AboutUs_Data.aspx.cs" Inherits="Admin_AboutUs_Data" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
<div align="center">
    <fieldset>
        <legend align="center" style="font-family:'Century Gothic';">
            <h1>AboutUs Data</h1>
        </legend>
    <br /><br />
    <table>
        <tr>
            <td>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="img" HeaderText="img" SortExpression="img" />
                        <asp:BoundField DataField="AU_Desc" HeaderText="AU_Desc" SortExpression="AU_Desc" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="delete from AboutUs where Id=@Id;" SelectCommand="SELECT * FROM [AboutUs]" UpdateCommand="update AboutUs set AU_Desc=@AU_Desc where Id=@Id;">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="AU_Desc" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </td>
        </tr>
    </table>
    </fieldset>
</div>
</asp:Content>

