<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true" CodeFile="ContactUs_Data.aspx.cs" Inherits="Admin_ContactUs_Data" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
<div align="center">
    <fieldset>
        <legend align="center" style="font-family:'Century Gothic';">
            <h1>ContactUs Data</h1>
        </legend>
    <br /><br />
<table>
    <tr>
        <td>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="cnm" HeaderText="cnm" SortExpression="cnm" />
                    <asp:BoundField DataField="onm" HeaderText="onm" SortExpression="onm" />
                    <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                    <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                    <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="delete from ContactUs where Id=@Id;" SelectCommand="SELECT * FROM [ContactUs]" UpdateCommand="update ContactUs set cnm=@cnm, onm=@onm, address=@address, email=@email, contact=@contact where Id=@Id;">
                <DeleteParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="cnm" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="onm" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="address" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="email" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="contact" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </td>
    </tr>
</table>
</fieldset>
</div>
</asp:Content>

